[tool.pyright]
include = ["config", "jabbariao"]
exclude = ["**/__pycache__"]
venv = "jabbariao_core"

pythonVersion = "3.10"

reportMissingImports = true
reportMissingTypeStubs = false

executionEnvironments = [
  { root = "config" },
  { root = "jabbariao"}
]
