[tool.pyright]
include = ["config", "jabbariao"]
exclude = ["**/node_modules",
    "**/__pycache__",
]
defineConstant = { DEBUG = true }
venv = "jabbariao_core"

pythonVersion = "3.10"

reportMissingImports = true
reportMissingTypeStubs = false
