[tool.pyright]
include = ["src"]
exclude = ["**/node_modules",
    "**/__pycache__",
]
defineConstant = { DEBUG = true }
venv = "jabbariao_core"

reportMissingImports = true
reportMissingTypeStubs = false
