# Generated by Django 4.1.7 on 2023-04-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["title"], name="title_index"),
        ),
    ]
