# Generated by Django 4.1.7 on 2023-04-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_title_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
