# Generated by Django 4.1.7 on 2023-04-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
